#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: complete_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  app:
    image: openjdk:17
    container_name: complete_app
    restart: always
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: ["java", "-jar", "kirana-1.0-SNAPSHOT.jar"]

volumes:
  postgres_data:
  mongo_data:
